my_resume/urls.py
from django.urls import path

from .views import MyPerson, MyAward, MyExperience, MyEducation, MySkills, Resume , MyProject, CreateAccount
from .views import EditPerson, EditSkills, EditAward, EditExperience, EditEducation, EditProject
from .views import CreateAccount, UpdateAccount, UserDelete, PasswordsChangeView
from .views import DeletePerson, DeleteAwards, DeleteEducation, DeleteExperience, DeleteProject, DeleteSkills, DeleteProject
from .views import Volunteers, EditVolunteers, DeleteVolunteers, ViewPDF, DownloadPDF, ResumeDone, Portfolio

urlpatterns = [
    path('add_person/', MyPerson.as_view(), name = 'create_user'),
    path('add_volunteer/', Volunteers.as_view(), name = 'create_volunteer'),
    path('edit_volunteer/<int:pk>', EditVolunteers, name = 'edit_volunteer'),
    path('delete_volunteer/<str:pk>/', DeleteVolunteers, name='delete_volunteer'),
    path('edit_person/<int:pk>', EditPerson, name = 'edit_user'),
    path('add_award/', MyAward.as_view(), name = 'create_award'),
    path('edit_award/<int:pk>', EditAward, name = 'edit_award'),
    path('add_experience/', MyExperience.as_view(), name = 'create_experience'),
    path('edit_experience/<int:pk>', EditExperience, name = 'edit_experience'),
    path('add_education/', MyEducation.as_view(), name = 'create_education'),
    path('edit_education/<int:pk>', EditEducation, name = 'edit_education'),
    path('add_skills/', MySkills.as_view(), name = 'create_skills'),
    path('edit_skills/<int:pk>', EditSkills, name = 'edit_skills'),
    path('add_project/', MyProject.as_view(), name = 'create_project'),
    path('edit_project/<int:pk>', EditProject, name = 'edit_project'),
    path('', Resume, name='resume'),
    path('resume_done', ResumeDone, name='resume_done'),
    path('register/', CreateAccount.as_view(), name='register'),
    path('edit_profile/', UpdateAccount.as_view(), name='update_account'),
    path('user_delete/', UserDelete, name = 'user_delete'),
    path('password/', PasswordsChangeView.as_view(template_name='registration/change-password.html'), name='change_password'),
    path('delete_person/<str:pk>/', DeletePerson, name='delete_user'),
    path('delete_education/<str:pk>/', DeleteEducation, name='delete_education'),
    path('delete_skills/<str:pk>/', DeleteSkills, name='delete_skills'),
    path('delete_experience/<str:pk>/', DeleteExperience, name='delete_experience'),
    path('delete_awards/<str:pk>/', DeleteAwards, name='delete_awards'),
    path('delete_project/<str:pk>/', DeleteProject, name='delete_project'),
    path('resume_preview', ViewPDF.as_view(), name='resume_preview'), 
    path('download_resume', DownloadPDF.as_view(), name='download_resume'),
    path('portfolio/<username>', Portfolio, name='portfolio'),
]

templates/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_resume.urls')),
    path('', include('django.contrib.auth.urls')),
    # path('', include('the_resume.urls')),
]

my_resume/models.py
from django.db import models
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
# Create your models here.

class Person(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    name = models.CharField(max_length= 25)
    location = models.CharField(max_length=200)
    email = models.EmailField()
    mobile_number = models.CharField(max_length=12)
    occupation = models.TextField()
    summary = models.TextField()
    site = models.CharField(max_length=700, null=True, blank=True)
    twitter_url = models.CharField(max_length=250, null = True, blank = True)
    github_url = models.CharField(max_length=250, null = True, blank = True)
    linkedin_url = models.CharField(max_length=250, null = True, blank = True)
    dribble_url = models.CharField(max_length=250, null = True, blank = True)
    figma_url = models.CharField(max_length=250, null = True, blank = True)
    codepen_url = models.CharField(max_length=250, null = True, blank = True)
    behance_url = models.CharField(max_length=250, null = True, blank = True)

    def get_absolute_url(self):
        return reverse('resume')

    def __str__ (self):
        return self.name

class Skills(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    name = models.CharField(max_length=30)

    def get_absolute_url(self):
        return reverse('resume')

    def __str__ (self):
        return self.name

class Experience(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    company_name = models.CharField(max_length=100)
    company_location = models.CharField(max_length=200)
    post_held = models.CharField(max_length=30)
    year_from = models.DateField()
    year_to = models.DateField(null=True, blank=True)
    info = models.TextField()

    def get_absolute_url(self):
        return reverse('resume')

    def __str__ (self):
        return self.company_name

class Education(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    school_name = models.CharField(max_length=30)
    school_location = models.CharField(max_length=150)
    degree = models.CharField(max_length=30)
    year_from = models.DateField()
    year_to = models.DateField(null=True, blank=True)
    info = models.TextField()

    def get_absolute_url(self):
        return reverse('resume')

    def __str__ (self):
        return self.school_name

class Awards(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    award = models.CharField(max_length=40)

    def get_absolute_url(self):
        return reverse('resume')

    def __str__ (self):
        return self.award

class Project(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    name = models.CharField(max_length=40)
    source_code = models.CharField(max_length=150, null = True, blank = True)
    live = models.CharField(max_length=150, null = True, blank = True)
    info = models.TextField(max_length=200)

    def get_absolute_url(self):
        return reverse('resume')

    def __str__ (self):
        return self.name

class Volunteer(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    post_held = models.CharField(max_length=30)
    organization = models.CharField(max_length=100)
    year_from = models.DateField()
    year_to = models.DateField(null=True, blank=True)
    info = models.TextField()

    def get_absolute_url(self):
        return reverse('resume')

    def __str__ (self):
        return self.post_held

my_resume/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.views import PasswordChangeView
from django.views import View

# import pdfkit
from django.http import HttpResponse
from django.template.loader import get_template
from io import BytesIO
from xhtml2pdf import pisa


from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView
from .models import Person, Awards, Education, Experience, Skills, Project, Volunteer
from .forms import  PersonForm, AwardForm, ExperienceForm, EducationForm, SkillsForm, ProjectForm, SignUpForm, EditAccountForm, PasswordChangingForm, VolunteerForm

# @login_required(login_url='login')
# def MyPerson(request):
#     context = {}
#     form = PersonForm
#     context['form'] = form

#     def form_valid(self, form):
#         person = form.save(commit=False)
#         person.user = self.request.user  
#         person.save()
#         return redirect('resume_done')

#     return render(request, 'create_user.html', context)

class MyPerson(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = Person
    form_class= PersonForm
    template_name= 'create_user.html'
    success_url= reverse_lazy('resume_done')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_queryset(self):
        return Person.objects.filter(user=self.request.user)

@login_required(login_url='login')
def EditPerson(request, pk):
        person = get_object_or_404(Person, pk=pk)
        form = PersonForm(instance=person)
        if request.method == 'POST':
            form = PersonForm(request.POST, instance=person)
            if form.is_valid():
                form.save()
                return redirect('resume_done')
        context = {'form':form}
        return render(request, 'create_user.html', context)


class MySkills(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = Skills
    form_class =SkillsForm
    template_name = 'create_skills.html'
    success_url = reverse_lazy('resume')

    def form_valid(self, form):
        experience = form.save(commit=False)
        experience.user = self.request.user  
        experience.save()
        return redirect('resume')

@login_required(login_url='login')
def EditSkills(request, pk):
        skills = get_object_or_404(Skills, pk=pk)
        form = SkillsForm(instance=skills)
        if request.method == 'POST':
            form = SkillsForm(request.POST, instance=skills)
            if form.is_valid():
                form.save()
                return redirect('resume_done')
        context = {'form':form}
        return render(request, 'create_skills.html', context)


class MyAward(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = Awards
    form_class = AwardForm
    template_name = 'create_award.html'

    def form_valid(self, form):
        experience = form.save(commit=False)
        experience.user = self.request.user  
        experience.save()
        return redirect('resume')

@login_required(login_url='login')
def EditAward(request, pk):
        award = get_object_or_404(Awards, pk=pk)
        form = AwardForm(instance=award)
        if request.method == 'POST':
            form = AwardForm(request.POST, instance=award)
            if form.is_valid():
                form.save()
                return redirect('resume_done')
        context = {'form':form}
        return render(request, 'create_award.html', context)


class MyExperience(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = Experience
    form_class = ExperienceForm
    template_name = 'create_experience.html'

    def form_valid(self, form):
        experience = form.save(commit=False)
        experience.user = self.request.user  
        experience.save()
        return redirect('resume')

@login_required(login_url='login')
def EditExperience(request, pk):
        experience = get_object_or_404(Experience, pk=pk)
        form = ExperienceForm(instance=experience)
        if request.method == 'POST':
            form = ExperienceForm(request.POST, instance=experience)
            if form.is_valid():
                form.save()
                return redirect('resume_done')
        context = {'form':form}
        return render(request, 'create_experience.html', context)


class MyEducation(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = Education
    form_class = EducationForm
    template_name = 'create_education.html'

    def form_valid(self, form):
        experience = form.save(commit=False)
        experience.user = self.request.user  
        experience.save()
        return redirect('resume')

@login_required(login_url='login')
def EditEducation(request, pk):
        education = get_object_or_404(Education, pk=pk)
        form = EducationForm(instance=education)
        if request.method == 'POST':
            form = EducationForm(request.POST, instance=education)
            if form.is_valid():
                form.save()
                return redirect('resume_done')
        context = {'form':form}
        return render(request, 'create_education.html', context)


class MyProject(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = Project
    form_class = ProjectForm
    template_name = 'create_project.html'
    success_url = reverse_lazy('resume')

    def form_valid(self, form):
        experience = form.save(commit=False)
        experience.user = self.request.user  
        experience.save()
        return redirect('resume')

@login_required(login_url='login')
def EditProject(request, pk):
        project = get_object_or_404(Project, pk=pk)
        form = ProjectForm(instance=project)
        if request.method == 'POST':
            form = ProjectForm(request.POST, instance=project)
            if form.is_valid():
                form.save()
                return redirect('resume_done')
        context = {'form':form}
        return render(request, 'create_project.html', context)


@login_required(login_url='login')
def Resume(request):
    education = Education.objects.filter(user = request.user)[:3]
    experience = Experience.objects.filter(user = request.user)[:5]
    person = Person.objects.filter(user = request.user)[:1]
    skills = Skills.objects.filter(user = request.user)[:7]
    awards = Awards.objects.filter(user = request.user)[:5]
    projects = Project.objects.filter(user = request.user)[:5]
    volunteer = Volunteer.objects.filter(user = request.user)[:5]
    return render(request, 'add_resume.html', {'education':education, 'experience':
        experience, 'person': person, 'skills':skills, 'awards': awards, 'projects': projects, 'volunteer':volunteer})



class CreateAccount(CreateView):
    form_class= SignUpForm
    template_name='registration/register.html'
    success_url= reverse_lazy('resume')

class UpdateAccount(LoginRequiredMixin, UpdateView):
    login_url = 'login'
    model = User
    form_class= EditAccountForm
    template_name='registration/edit_profile.html'
    success_url= reverse_lazy('blog_list')

    def get_object(self):
        return self.request.user

@login_required(login_url='login')
def UserDelete(request):
     user = request.user
     if request.method == 'POST':
                user.delete()
                return redirect('login')


class PasswordsChangeView(LoginRequiredMixin, PasswordChangeView):
    login_url = 'login'
    form_class = PasswordChangingForm
    success_url = reverse_lazy('password_success')

@login_required(login_url='login')
def DeletePerson(request, pk):
	person  = Person .objects.get(id=pk)
	person.delete()
	return redirect('resume')

@login_required(login_url='login')
def DeleteSkills(request, pk):
	skills =Skills.objects.get(id=pk)
	skills.delete()
	return redirect('resume')

@login_required(login_url='login')
def DeleteExperience(request, pk):
	experience = Experience.objects.get(id=pk)
	experience.delete()
	return redirect('resume')

@login_required(login_url='login')
def DeleteEducation(request, pk):
	education = Education.objects.get(id=pk)
	education.delete()
	return redirect('resume')

@login_required(login_url='login')
def DeleteAwards(request, pk):
	queryset = Awards.objects.get(id=pk)
	queryset.delete()
	return redirect('resume')

@login_required(login_url='login')
def DeleteProject(request, pk):
	project = Project.objects.get(id=pk)
	project.delete()
	return redirect('resume')

class Volunteers(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = Volunteer
    form_class = VolunteerForm
    template_name = 'create_volunteer.html'
    success_url = reverse_lazy('resume')

    def form_valid(self, form):
        volunteer = form.save(commit=False)
        volunteer.user = self.request.user  
        volunteer.save()
        return redirect('resume')


@login_required(login_url='login')
def EditVolunteers(request, pk):
        volunteer = get_object_or_404(Volunteer, pk=pk)
        form = VolunteerForm(instance=volunteer)
        if request.method == 'POST':
            form = VolunteerForm(request.POST, instance=volunteer)
            if form.is_valid():
                form.save()
                return redirect('resume_done')
        context = {'form':form}
        return render(request, 'create_volunteer.html', context)

@login_required(login_url='login')
def DeleteVolunteers(request, pk):
	volunteer = Volunteer.objects.get(id=pk)
	volunteer.delete()
	return redirect('resume')

def render_to_pdf(template_src, context_dict={}):
	template = get_template(template_src)
	html  = template.render(context_dict)
	result = BytesIO()

my_resume/templates/add_resume.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Resume</title>
</head>
<body>
{% block content %}
<div style="margin-top: 20px;">
    {% if person %}
<div style="margin-bottom: 60px;" class="row">
    <div class="col">
    <ul style="list-style: none; padding: 0;">
            {% for a_person in person %}
            <h2 style="display: inline-block;"><li>{{ a_person }}</li></h2>
            <p style="font-size: 20px;"> {{ a_person.occupation }}</p>
    

            <a href="{% url 'edit_user' a_person.pk %}"><span class="material-icons">mode_edit</span</a>
            <a href="{% url 'delete_user' a_person.pk %}"><span class="material-icons">delete</span></a>

    </ul>
</div>
    <div class="col">

            <div style="margin-left: 20px;">
            <a style="color: black;" href="{{ a_person.site }}">{{ a_person.site }}</a><br>
            {{a_person.location}}<br>
            {{a_person.email }}<br>
            {{ a_person.mobile_number }}
            </div>          
    </div>
            <h5 style="margin-top: 15px;">About Me Summary</h5>
            <div style="width: 500px; margin-right: 700px;">
             {{ a_person.summary }}
            </div>
</div>
{% endfor %}
{% else %}
<h3 style="margin-bottom: 50px;">Add <a href="{% url 'create_user' %}">Profile</a></h3>
{% endif %}
</div> 

<div class="row"> 
    <div class="col">

                <h3 style="margin-bottom: 20px;">Skills<a href="{% url 'create_skills'%}"><span class="material-icons">add</span></a></h3>
<ul>
    {% for a_skill in skills %}
   <li><h5 style="display: inline-block;">{{ a_skill }}</h5>
    <a href="{% url 'edit_skills' a_skill.pk  %}"><span class="material-icons">mode_edit</span></a>   
    <a href="{% url 'delete_skills'  a_skill.pk %}"> <span class="material-icons">delete</span></a>
</li>
    {% endfor %}
</ul>

        <h3 style="margin-bottom: 20px;">Experience<a href="{% url 'create_experience'%}"><span class="material-icons">add</span></a></h3>
<ul>
    {% for an_experience in experience %}

    <li style="padding-right: 50px;"><h5 style="display: inline-block;">{{ an_experience }} - </h5> {{ an_experience.company_location }}</li>

    <a href="{% url 'edit_experience' an_experience.pk %}"><span class="material-icons">mode_edit</span></a>
    <a href="{% url 'delete_experience' an_experience.pk %}"> <span class="material-icons">delete</span></a>
            
    <p style="margin-bottom: 3px; font-weight: 500;">{{ an_experience.post_held }}</p>
    <small>{{an_experience.year_from|date:"M, Y" }} - {% if an_experience.year_to is none %}Ongoing{% else %} {{ an_experience.year_to|date:"M, Y" }} {% endif %}</small>
    <div style="padding-right: 50px; margin-top: 15px; margin-bottom: 30px;">
        {{ an_experience.info }}
    </div>
    {% endfor %}
</ul>


<h3 style="margin-bottom: 20px;">Projects<a href="{% url 'create_project'%}"><span class="material-icons">add</span></a></h3>
<ul>
    {% for project in projects %}
    <li style="padding-right: 50px;"><h5>{{ project }}</h5></li>
    <a href="{% url 'edit_project' project.pk %}"><span class="material-icons">mode_edit</span></a>
    <a href="{% url 'delete_project' project.pk %}"> <span class="material-icons">delete</span></a>

    <p><a href="{{project.source_code}}"><b>Source Code</b></a>
    <a href="{{project.live}}"><b>Live</b></a></p>
    <div style="padding-right: 50px; margin-top: 15px; margin-bottom: 30px;">
        {{ project.info }}
    </div> 
    {% endfor %}
</ul>


    </div>

    

    <div class="col">

<h3 style="margin-bottom: 20px;">Education<a href="{% url 'create_education'%}"><span class="material-icons">add</span></a></h3>
<ul>
    {% for an_education in education %}
    <li><h5 style="display: inline-block;">{{ an_education }}  -</h5> {{an_education.school_location }}</li>
    
    <a href="{% url 'edit_education' an_education.pk %}"><span class="material-icons">mode_edit</span></a>
    <a href="{% url 'delete_education' an_education.pk %}"> <span class="material-icons">delete</span></a>

    <p style="margin-bottom: 3px; font-weight: 500;">{{ an_education.degree }}</p>
    <small>{{an_education.year_from|date:"M, Y" }} - {% if an_education.year_to is none %}Ongoing{% else %} {{ an_education.year_to|date:"M, Y" }} {% endif %}</small>
    <div style="padding-right: 50px; margin-top: 15px; margin-bottom: 30px;">
        {{ an_education.info }}
    </div> 
    {% endfor %}
</ul>




        <h3 style="margin-bottom: 20px; margin-top: 40px; ">Awards<a href="{% url 'create_award'%}"><span class="material-icons">add</span></a></h3>

<ul>
    {% for a_award in awards %}
    <li><h5  style="display: inline-block;">{{ a_award }}</h5>

    <a href="{% url 'edit_award' a_award.pk  %}"><span class="material-icons">mode_edit</span></a>   
    <a href="{% url 'delete_awards' a_award.pk %}"><span id="delete-icon" class="material-icons">delete</span></a>

    </li>
    {% endfor %}
</ul>




        <h3 style="margin-bottom: 20px; margin-top: 40px;">Volunteering<a href="{% url 'create_volunteer' %}"><span class="material-icons">add</span></a></h3>

<ul>
{% for a_volunteer in volunteer %}
<li><h5  style="display: inline-block;">{{ a_volunteer }}</h5></li>
  <a href="{% url 'edit_volunteer' a_volunteer.pk %}"><span class="material-icons">mode_edit</span></a>   
  <a href="{% url 'delete_volunteer' a_volunteer.pk %}"><span id="delete-icon" class="material-icons">delete</span></a>

  <p style="margin-bottom: 3px; font-weight: 500;">{{ a_volunteer.organization }}</p>
  <small>{{a_volunteer.year_from|date:"M, Y" }} - {% if a_volunteer.year_to is none %}Ongoing{% else %} {{ a_volunteer.year_to|date:"M, Y" }} {% endif %}</small>
  <div style="padding-right: 50px; margin-top: 15px; margin-bottom: 30px;">
        {{ a_volunteer.info }}
    </div>
{% endfor %}
</ul>

    </div>
</div>


{% endblock %}
</body>
</html>

my_resume/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resume Generator</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
  
</head>
<body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'resume' %}">Resume-Portfolio Builder</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarContent">
              {% if user.is_authenticated %}
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'resume_done' %}">My Resume</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'portfolio' user %}">My Portfolio</a>
                      </li>
                  </ul>

                  <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.first_name|title }} {{user.last_name|title }}</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'update_account'%}">Account Settings</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                        </ul>
                    </li>
                </ul>
              {% else %}
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">My Resume</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

my_resume/templates/create_award.html
{% extends 'base.html' %} {% block content %}

<h2 style="margin-bottom: 20px">Award Form</h2>
<div class="form-group">
  <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Post</button>
  </form>
</div>
{% endblock %}

my_resume/templates/create_education.html
{% extends 'base.html' %} {% block content %}

<h2 style="margin-bottom: 20px">Education Form</h2>
<div class="form-group">
  <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Post</button>
  </form>
</div>
<script>
  $(function () {
    $("#id_year_from").datepicker();
  });
</script>

<script>
  $(function () {
    $("#id_year_to").datepicker();
  });
</script>
{% endblock %}

my_resume/templates/create_experience.html
{% extends 'base.html' %} {% block content %}

<div class="form-group">
  <h2 style="margin-bottom: 20px">Experience Form</h2>
  <form method="POST">
    {% csrf_token %} {{ form.as_p}}
    <button class="btn btn-primary" type="submit">Post</button>
  </form>
</div>
<script>
  $(function () {
    $("#id_year_from").datepicker();
  });
</script>

<script>
  $(function () {
    $("#id_year_to").datepicker();
  });
</script>
{% endblock %}

my_resume/templates/create_project.html
{% extends 'base.html' %} {% block content %}

<h2 style="margin-bottom: 20px">Add Project</h2>
<div class="form-group">
  <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Post</button>
  </form>
</div>
{% endblock %}

my_resume/templates/create_skills.html
{% extends 'base.html' %} {% block content %}

<h2 style="margin-bottom: 20px">Skills Form</h2>
<div class="form-group">
  <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Post</button>
  </form>
</div>
{% endblock %}

my_resume/templates/create_volunteer.html
{% extends 'base.html' %} {% block content %}

<h2 style="margin-bottom: 20px">Add Project</h2>
<div class="form-group">
  <form method="POST">
    {% csrf_token %} {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Post</button>
  </form>
</div>
<script>
  $(function () {
    $("#id_year_from").datepicker();
  });
</script>

<script>
  $(function () {
    $("#id_year_to").datepicker();
  });
</script>
{% endblock %}